### PR TITLE
Autoload extension on .log page

### PR DESCRIPTION
**Pull request by AverageMarcus**
Automatically trigger the extension if viewing a page ending in `.log`

### CODE REVIEW

**Comment by rluvaton** [comment]
This is great, thanks for your contribution, in the future we should add option to disable it

**Comment by AverageMarcus** [comment]
Yeah, this is my first time working with browser extensions so wasn't too sure how to go about handling the settings. 

Thanks so much for the great extension!

**Comment by rluvaton** [comment]
Always!, you can checkout my other open source projects if you want

It would be great if you could add the setting page

**Comment by rluvaton** [comment]
because of the new permission that is needed I needed for the extension to be review again, only after that I can publish the new package

**Comment by rluvaton** [comment]
Also a rating would be great so other people could see that too

**Comment by rluvaton** [comment]
deployed

**Pull request merged**
